Require -lintl
On FreeBSD, -lintl is required to link against libintl.

If missing, gcc linker raises undefined reference to libintl_gettext.

Reference:
https://www.gnu.org/software/gettext/FAQ.html#integrating_undefined